# Generated by Django 4.1.2 on 2022-11-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_rename_links_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='video_url',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
