# Generated by Django 4.1.2 on 2022-11-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_link_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
